### ISSUE TITLE
ScanBytesTrigrams slice bounds out of range

### ISSUE THREAD

**Issue by moorereason** [dgryski/go-simstore#13]
I received a `panic: runtime error: slice bounds out of range` on [scanners.go#L46](https://github.com/dgryski/go-simstore/blob/905aab9be12a17638476ade1192ab714e170f4bf/simhash/scanners.go#L46).

This issue is very interesting since, at first glance, that line should get OOB at the end of every string since `atEOF` is false and `len(data)` goes less than 3.  I'm very curious to hear an explanation.  I'm assuming there's a slice behind the `data` slice that keeps this code from blowing up every time.

Anyway, you can trigger the panic from `TestSimHash` with the following addition:

```go
h4 := simhashString(strings.Repeat("Now is the winter", 241)) // length = 4097
fmt.Printf("h=%016x\n", h4)
```
The panic only occurs for me when the string size hits 4096+.

I'm on Go v1.5.1 linux/amd64.

**Comment by dgryski** [comment]
Thanks for the report!
