### ISSUE TITLE
Empty simstore causes panic

### ISSUE THREAD

**Issue by zathey** [dgryski/go-simstore#15]
`panic: runtime error: invalid memory address or nil pointer dereference`

Test code:
```
ss := simstore.New6(0, simstore.NewU64Slice)
ss.Finish()
```
`github.com/dgryski/go-simstore/simstore.go:184`

```
ss := simstore.New6(0, simstore.NewU64Slice)
ss.Find(0)
```
`github.com/dgryski/go-simstore/simstore6.go:141`

**Comment by dgryski** [comment]
I'll look at this tomorrow (Thursday).
