### ISSUE TITLE
What are the four stores that differ in their space? Still feature, or other?

### ISSUE THREAD

**Issue by wpecker** [dgryski/go-simstore#21]
```
store = simstore.New3Small(sigsEstimate)
store = simstore.New3(sigsEstimate, factory)
store = simstore.New6(sigsEstimate, factory)
vpt = vptree.New(items)

```

**Comment by dgryski** [comment]
"New3" and "New3Small" both store hashes and can detect similar hashes with at most 3 differing bits.  They differ in the amount of space used, trading (approximately) for computation time.

"New6" is much much larger, but allows detecting bits with up to 6 differing bits.

The VP Tree allows detecting the "closest" matches by hamming distance, with no limit on *how* different the keys are.

I will update the documentation to clarify these tradeoffs.

**Comment by wpecker** [comment]
@dgryski  Thanks
